# Generated by Django 4.1.2 on 2022-12-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0003_alter_patient_condition_date_diagnosed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='state',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='zip',
        ),
        migrations.CreateModel(
            name='Patient_Favorite_Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepages.food')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepages.patient')),
            ],
            options={
                'db_table': 'patient_favorite_food',
            },
        ),
    ]
