# Generated by Django 4.1.3 on 2022-12-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0004_remove_patient_address1_remove_patient_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
