# Generated by Django 4.1.2 on 2022-12-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0004_remove_patient_address1_remove_patient_address2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_condition',
            name='date_diagnosed',
        ),
    ]
