# Generated by Django 4.1.3 on 2022-12-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0005_alert_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_favorite_food',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
