# Generated by Django 4.1.3 on 2022-12-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0006_patient_favorite_food_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_type',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
