# Generated by Django 4.1.2 on 2022-12-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0005_remove_patient_condition_date_diagnosed'),
        ('homepages', '0006_patient_favorite_food_is_favorite'),
    ]

    operations = [
    ]
