# Generated by Django 4.1.3 on 2022-12-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0007_alter_alert_type_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert_type',
            name='name',
            field=models.CharField(default='none', max_length=25),
        ),
    ]
