# Generated by Django 4.1.3 on 2022-12-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0005_remove_patient_condition_date_diagnosed'),
        ('homepages', '0009_alter_alert_type_description'),
    ]

    operations = [
    ]
