# Generated by Django 4.1.2 on 2022-12-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0007_merge_20221201_2215'),
        ('homepages', '0010_merge_20221202_0434'),
    ]

    operations = [
    ]
