# Generated by Django 4.1.3 on 2022-12-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0010_alter_food_food_name'),
        ('homepages', '0011_merge_20221202_0656'),
    ]

    operations = [
    ]
